import { expect, test, describe } from "bun:test";
import { buildToolchainUpdateIssueBody } from "./toolchain_update_body_builder";

describe("Toolchain Update Body Builder", () => {
  test("generates full report with all types of issues", () => {
    const body = buildToolchainUpdateIssueBody([
      {
        filePath: "crates/typstlab-base/src/version_resolver_jsons/typst.json",
        baseUrl: "https://github.com/typst/typst",
        versionPattern: "v{version}",
        releaseVersions: ["0.14.3", "0.14.1"],
        ignoredVersions: ["0.13.1"],
        versionChecks: [
          {
            typstVersion: "0.14.3",
            missingVersions: ["0.14.1"],
            extraVersions: [],
            duplicateVersions: []
          },
          {
            typstVersion: "0.14.1",
            missingVersions: [],
            extraVersions: [],
            duplicateVersions: []
          }
        ],
        ignoreCheck: {
          extraVersions: ["0.99.0"],
          duplicateVersions: ["0.13.1"]
        }
      },
      {
        filePath: "crates/typstlab-base/src/version_resolver_jsons/type_docs.json",
        baseUrl: "https://github.com/typst-community/dev-builds",
        versionPattern: "docs-v{version}",
        releaseVersions: ["0.14.3", "0.14.1"],
        ignoredVersions: [],
        versionChecks: [
          {
            typstVersion: "0.14.3",
            missingVersions: [],
            extraVersions: ["0.99.0"],
            duplicateVersions: []
          }
        ],
        ignoreCheck: {
          extraVersions: [],
          duplicateVersions: []
        }
      }
    ]);

    const expected =
      `# 🔍 Toolchain Update Report

This report checks whether resolver JSON values match the releases of the configured GitHub repositories.

## typst/typst

Path: \`crates/typstlab-base/src/version_resolver_jsons/typst.json\`
Base URL: \`https://github.com/typst/typst\`
Version pattern: \`v{version}\`

##### \`0.14.3\`
###### ❌ Missing versions
\`0.14.1\`

##### \`ignores\`
###### ⚠️ Extra versions
\`0.99.0\`

###### ⚠️ Duplicate versions
\`0.13.1\`

---

## typst-community/dev-builds

Path: \`crates/typstlab-base/src/version_resolver_jsons/type_docs.json\`
Base URL: \`https://github.com/typst-community/dev-builds\`
Version pattern: \`docs-v{version}\`

##### \`0.14.3\`
###### ⚠️ Extra versions
\`0.99.0\`

---
*This issue was automatically generated by the CI toolchain monitor.*`;

    expect(body).toBe(expected);
  });

  test("produces a stable footer", () => {
    const body = buildToolchainUpdateIssueBody([]);

    const expected =
      `# 🔍 Toolchain Update Report

This report checks whether resolver JSON values match the releases of the configured GitHub repositories.

---
*This issue was automatically generated by the CI toolchain monitor.*`;

    expect(body).toBe(expected);
  });
});
