import { expect, test, describe } from "bun:test";
import { buildToolchainUpdateIssueBody } from "./toolchain_update_body_builder";

describe("Toolchain Update Body Builder", () => {
  test("generates a full report for one file", () => {
    const body = buildToolchainUpdateIssueBody([
      {
        filePath: "crates/typstlab-base/src/version_resolver_jsons/typst.json",
        repoName: "typst/typst",
        baseUrl: "https://github.com/typst/typst",
        versionPattern: "v{version}",
        releaseVersions: ["0.14.3", "0.14.2", "0.14.1", "0.14.0"],
        ignoredVersions: ["0.14.0", "0.99.0"],
        missingVersions: ["0.14.1"],
        extraVersions: ["0.13.0"],
        duplicateValueVersions: [
          {
            version: "0.14.2",
            assignments: [
              { typstVersion: "0.14.3", count: 1 },
              { typstVersion: "0.14.2", count: 1 }
            ]
          }
        ],
        ignoredVersionsNotInReleases: ["0.99.0"],
        ignoredVersionsPresentInValues: ["0.14.0"],
        duplicateIgnoredVersions: ["0.14.0"]
      }
    ]);

    const expected =
      `# 🔍 Toolchain Update Report

This report checks whether resolver JSON values match the releases of the configured GitHub repositories.

## typst/typst

Path: \`crates/typstlab-base/src/version_resolver_jsons/typst.json\`
Base URL: \`https://github.com/typst/typst\`
Version pattern: \`v{version}\`

### Missing versions
\`0.14.1\`

### Extra versions
\`0.13.0\`

### Duplicate versions in JSON values

| value | keys |
| --- | --- |
| \`0.14.2\` | \`0.14.3\`, \`0.14.2\` |

### Ignored versions still present in JSON values
\`0.14.0\`

### Ignored versions not found in releases
\`0.99.0\`

### Duplicate ignores
\`0.14.0\`

---
*This issue was automatically generated by the CI toolchain monitor.*`;

    expect(body).toBe(expected);
  });

  test("separates multiple file sections with repo titles", () => {
    const body = buildToolchainUpdateIssueBody([
      {
        filePath: "crates/typstlab-base/src/version_resolver_jsons/typst.json",
        repoName: "typst/typst",
        baseUrl: "https://github.com/typst/typst",
        versionPattern: "v{version}",
        releaseVersions: ["0.14.3"],
        ignoredVersions: [],
        missingVersions: ["0.14.3"],
        extraVersions: [],
        duplicateValueVersions: [],
        ignoredVersionsNotInReleases: [],
        ignoredVersionsPresentInValues: [],
        duplicateIgnoredVersions: []
      },
      {
        filePath: "crates/typstlab-base/src/version_resolver_jsons/typstyle.json",
        repoName: "typstyle-rs/typstyle",
        baseUrl: "https://github.com/typstyle-rs/typstyle",
        versionPattern: "v{version}",
        releaseVersions: ["0.14.3"],
        ignoredVersions: [],
        missingVersions: [],
        extraVersions: ["0.13.0"],
        duplicateValueVersions: [],
        ignoredVersionsNotInReleases: [],
        ignoredVersionsPresentInValues: [],
        duplicateIgnoredVersions: []
      }
    ]);

    expect(body).toContain("## typst/typst");
    expect(body).toContain("## typstyle-rs/typstyle");
    expect(body).toContain("\n---\n\n## typstyle-rs/typstyle");
  });
});
