import type { ToolchainFileCheckResult } from "./toolchain_update_checker";

function formatInlineVersions(versions: string[], separator = " "): string {
  return versions.map((version) => `\`${version}\``).join(separator);
}

function buildFileSection(file: ToolchainFileCheckResult): string[] {
  const sections: string[] = [];
  const repoName = file.baseUrl.replace(/^https:\/\/github\.com\//, "");
  const issueChecks = file.versionChecks.filter(
    (check) => check.missingVersions.length > 0 || check.extraVersions.length > 0 || check.duplicateVersions.length > 0
  );

  sections.push(`## ${repoName}`);
  sections.push("");
  sections.push(`Path: \`${file.filePath}\``);
  sections.push(`Base URL: \`${file.baseUrl}\``);
  sections.push(`Version pattern: \`${file.versionPattern}\``);
  sections.push("");

  for (const check of issueChecks) {
    sections.push(`##### \`${check.typstVersion}\``);

    if (check.missingVersions.length > 0) {
      sections.push("###### ❌ Missing versions");
      sections.push(formatInlineVersions(check.missingVersions, ", "));
      sections.push("");
    }

    if (check.extraVersions.length > 0) {
      sections.push("###### ⚠️ Extra versions");
      sections.push(formatInlineVersions(check.extraVersions, ", "));
      sections.push("");
    }

    if (check.duplicateVersions.length > 0) {
      sections.push("###### ⚠️ Duplicate versions");
      sections.push(formatInlineVersions(check.duplicateVersions, ", "));
      sections.push("");
    }
  }

  if (file.ignoreCheck.extraVersions.length > 0 || file.ignoreCheck.duplicateVersions.length > 0) {
    sections.push("##### `ignores`");

    if (file.ignoreCheck.extraVersions.length > 0) {
      sections.push("###### ⚠️ Extra versions");
      sections.push(formatInlineVersions(file.ignoreCheck.extraVersions, ", "));
      sections.push("");
    }

    if (file.ignoreCheck.duplicateVersions.length > 0) {
      sections.push("###### ⚠️ Duplicate versions");
      sections.push(formatInlineVersions(file.ignoreCheck.duplicateVersions, ", "));
      sections.push("");
    }
  }

  return sections;
}

export function buildToolchainUpdateIssueBody(files: ToolchainFileCheckResult[]): string {
  const sections: string[] = [];

  sections.push("# 🔍 Toolchain Update Report");
  sections.push("");
  sections.push("This report checks whether resolver JSON values match the releases of the configured GitHub repositories.");
  sections.push("");

  files.forEach((file, index) => {
    sections.push(...buildFileSection(file));
    if (index < files.length - 1) {
      sections.push("---");
      sections.push("");
    }
  });

  sections.push("---");
  sections.push("*This issue was automatically generated by the CI toolchain monitor.*");

  return sections.join("\n");
}
