import type { ConsistencyResult } from "./typst_consistency";
import type { JsonKeyCheckResult } from "./json_key_checker";

function formatInlineVersions(versions: string[], separator = " "): string {
  return versions.map((v) => `\`${v}\``).join(separator);
}

function buildJsonKeyAppendix(keyCheckResult: JsonKeyCheckResult): string[] {
  if (keyCheckResult.files.length === 0) {
    return [];
  }

  const sections: string[] = [];
  sections.push("### Appendix: Resolver JSON Key Check");
  sections.push("");
  sections.push("> Use the schema's `required` set as the source of truth and check each JSON file for missing or extra keys.");
  sections.push("");

  for (const file of keyCheckResult.files) {
    sections.push(`#### \`${file.filePath}\``);
    sections.push("");

    if (file.missingKeys.length > 0) {
      sections.push("##### ❌ Missing keys");
      sections.push(formatInlineVersions(file.missingKeys, ", "));
      sections.push("");
    }

    if (file.extraKeys.length > 0) {
      sections.push("##### ⚠️ Extra keys");
      sections.push(formatInlineVersions(file.extraKeys, ", "));
      sections.push("");
    }
  }

  return sections;
}

/**
 * Builds a Markdown body for the consistency check report.
 */
export function buildConsistencyIssueBody(
  result: ConsistencyResult,
  keyCheckResult: JsonKeyCheckResult,
  schemaPath: string
): string {
  const sections: string[] = [];

  sections.push("## 🔍 Typst Schema Consistency Report");
  sections.push("");
  sections.push(`Source file: \`${schemaPath}\``);
  sections.push("");
  sections.push("Automatic consistency check between GitHub releases and `typst_version_schema.json` properties.");
  sections.push("");

  if (result.missingInSchema.length > 0) {
    sections.push("### ❌ Missing Versions in `properties` (New releases found)");
    sections.push("The following versions exist on GitHub but are NOT defined in the schema properties:");
    sections.push(formatInlineVersions(result.missingInSchema));
    sections.push("");
  }

  if (result.extraInSchema.length > 0) {
    sections.push("### ⚠️ Extra Versions in `properties` (Not found on GitHub)");
    sections.push("The following versions are defined in the schema but do NOT exist as GitHub releases (possible typos):");
    sections.push(formatInlineVersions(result.extraInSchema));
    sections.push("");
  }

  if (result.missingInRequired.length > 0) {
    sections.push("### ❌ Missing in `required` list");
    sections.push("The following versions are defined in `properties` but are missing from the `required` array:");
    sections.push(formatInlineVersions(result.missingInRequired));
    sections.push("");
  }

  if (result.extraInRequired.length > 0) {
    sections.push("### ❌ Extra Versions in `required` list");
    sections.push("The following versions are present in the `required` array but are missing from `properties`:");
    sections.push(formatInlineVersions(result.extraInRequired));
    sections.push("");
  }

  if (result.ignoredInProperties.length > 0 || result.ignoredInRequired.length > 0) {
    sections.push("### ⚠️ Ignored Versions Still Present in Schema");

    if (result.ignoredInProperties.length > 0) {
      sections.push("The following versions are listed in `version_ignores` but still appear in `properties`:");
      sections.push(formatInlineVersions(result.ignoredInProperties));
      sections.push("");
    }

    if (result.ignoredInRequired.length > 0) {
      sections.push("The following versions are listed in `version_ignores` but still appear in `required`:");
      sections.push(formatInlineVersions(result.ignoredInRequired));
      sections.push("");
    }
  }

  sections.push(...buildJsonKeyAppendix(keyCheckResult));

  sections.push("---");
  sections.push("*This issue was automatically generated by the CI consistency check script.*");

  return sections.join("\n");
}
