import type { ToolchainDuplicateVersionResult, ToolchainFileCheckResult } from "./toolchain_update_checker.ts";

function formatInlineVersions(versions: string[], separator = " "): string {
  return versions.map((version) => `\`${version}\``).join(separator);
}

function formatDuplicateTable(duplicates: ToolchainDuplicateVersionResult[]): string[] {
  const rows = duplicates.map((duplicate) => {
    const keys = duplicate.assignments
      .map((assignment) => {
        const suffix = assignment.count > 1 ? ` x${assignment.count}` : "";
        return `\`${assignment.typstVersion}\`${suffix}`;
      })
      .join(", ");

    return `| \`${duplicate.version}\` | ${keys} |`;
  });

  return ["| value | keys |", "| --- | --- |", ...rows];
}

function buildFileSection(file: ToolchainFileCheckResult): string[] {
  const sections: string[] = [];

  sections.push(`## ${file.repoName}`);
  sections.push("");
  sections.push(`Path: \`${file.filePath}\``);
  sections.push(`Base URL: \`${file.baseUrl}\``);
  sections.push(`Version pattern: \`${file.versionPattern}\``);
  sections.push("");

  if (file.missingVersions.length > 0) {
    sections.push("### Missing versions");
    sections.push(formatInlineVersions(file.missingVersions, ", "));
    sections.push("");
  }

  if (file.extraVersions.length > 0) {
    sections.push("### Extra versions");
    sections.push(formatInlineVersions(file.extraVersions, ", "));
    sections.push("");
  }

  if (file.duplicateValueVersions.length > 0) {
    sections.push("### Duplicate versions in JSON values");
    sections.push("");
    sections.push(...formatDuplicateTable(file.duplicateValueVersions));
    sections.push("");
  }

  if (file.ignoredVersionsPresentInValues.length > 0) {
    sections.push("### Ignored versions still present in JSON values");
    sections.push(formatInlineVersions(file.ignoredVersionsPresentInValues, ", "));
    sections.push("");
  }

  if (file.ignoredVersionsNotInReleases.length > 0) {
    sections.push("### Ignored versions not found in releases");
    sections.push(formatInlineVersions(file.ignoredVersionsNotInReleases, ", "));
    sections.push("");
  }

  if (file.duplicateIgnoredVersions.length > 0) {
    sections.push("### Duplicate ignores");
    sections.push(formatInlineVersions(file.duplicateIgnoredVersions, ", "));
    sections.push("");
  }

  return sections;
}

export function buildToolchainUpdateIssueBody(files: ToolchainFileCheckResult[]): string {
  const sections: string[] = [];

  sections.push("# 🔍 Toolchain Update Report");
  sections.push("");
  sections.push("This report checks whether resolver JSON values match the releases of the configured GitHub repositories.");
  sections.push("");

  files.forEach((file, index) => {
    sections.push(...buildFileSection(file));
    if (index < files.length - 1) {
      sections.push("---");
      sections.push("");
    }
  });

  sections.push("---");
  sections.push("*This issue was automatically generated by the CI toolchain monitor.*");

  return sections.join("\n");
}
