use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let binary_dir = manifest_dir.join("src").join("binary");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", binary_dir.display());

    let tools = discover_tools(&binary_dir);
    let registry = generate_binary_registry(&tools);
    fs::write(out_dir.join("binary_registry.rs"), registry).unwrap();
}

fn discover_tools(binary_dir: &Path) -> Vec<(String, PathBuf)> {
    let mut tools = fs::read_dir(binary_dir)
        .unwrap()
        .filter_map(Result::ok)
        .filter(|entry| entry.file_type().map(|ty| ty.is_dir()).unwrap_or(false))
        .map(|entry| {
            let name = entry.file_name().to_str().unwrap().to_string();
            let module_path = entry.path().join("mod.rs");

            if !module_path.exists() {
                panic!(
                    "binary tool '{}' is missing required file: {}",
                    name,
                    module_path.display()
                );
            }

            (name, module_path)
        })
        .collect::<Vec<_>>();

    tools.sort_by(|left, right| left.0.cmp(&right.0));
    tools
}

fn generate_binary_registry(tools: &[(String, PathBuf)]) -> String {
    let mut output = String::new();
    output.push_str("// @generated by build.rs\n");

    for (name, path) in tools {
        output.push_str(&format!(
            "#[path = {}]\npub mod {name};\n",
            rust_string_literal(&path.to_string_lossy())
        ));
    }

    output.push_str("\npub static TOOLS: &[&dyn BinaryTool] = &[\n");
    for (name, _) in tools {
        output.push_str(&format!("    &{name}::TOOL,\n"));
    }
    output.push_str("];\n");

    output.push_str("\n#[cfg(test)]\npub fn assert_command_contracts() {\n");
    for (name, _) in tools {
        output.push_str(&format!(
            "    crate::command::assert_raw_command_factory(&{name}::COMMAND);\n"
        ));
    }
    output.push_str("}\n");

    output
}

fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}
