import { expect, test, describe } from "bun:test";
import { buildConsistencyIssueBody } from "./typst_consistency_body_builder";

describe("Consistency Issue Body Builder", () => {
  const emptyKeyCheckResult = { files: [] };

  test("generates minimal report when empty", () => {
    const result = {
      missingInSchema: [],
      extraInSchema: [],
      missingInRequired: [],
      extraInRequired: [],
      ignoredInProperties: [],
      ignoredInRequired: []
    };
    const body = buildConsistencyIssueBody(
      result,
      emptyKeyCheckResult,
      "crates/typstlab-base/src/version_resolver_jsons/typst_version_schema.json"
    );

    const expected =
      `## 🔍 Typst Schema Consistency Report

Source file: \`crates/typstlab-base/src/version_resolver_jsons/typst_version_schema.json\`

Automatic consistency check between GitHub releases and \`typst_version_schema.json\` properties.

---
*This issue was automatically generated by the CI consistency check script.*`;

    expect(body).toBe(expected);
  });

  test("generates report with missing versions", () => {
    const result = {
      missingInSchema: ["0.15.0", "0.15.1"],
      extraInSchema: [],
      missingInRequired: [],
      extraInRequired: [],
      ignoredInProperties: [],
      ignoredInRequired: []
    };
    const body = buildConsistencyIssueBody(
      result,
      emptyKeyCheckResult,
      "crates/typstlab-base/src/version_resolver_jsons/typst_version_schema.json"
    );

    const expected =
      `## 🔍 Typst Schema Consistency Report

Source file: \`crates/typstlab-base/src/version_resolver_jsons/typst_version_schema.json\`

Automatic consistency check between GitHub releases and \`typst_version_schema.json\` properties.

### ❌ Missing Versions in \`properties\` (New releases found)
The following versions exist on GitHub but are NOT defined in the schema properties:
\`0.15.0\` \`0.15.1\`

---
*This issue was automatically generated by the CI consistency check script.*`;

    expect(body).toBe(expected);
  });

  test("generates full report with all types of issues", () => {
    const result = {
      missingInSchema: ["0.15.0"],
      extraInSchema: ["0.14.99"],
      missingInRequired: ["0.14.2"],
      extraInRequired: ["0.15.0"],
      ignoredInProperties: ["0.11.1"],
      ignoredInRequired: ["0.11.1"]
    };
    const keyCheckResult = {
      files: [
        {
          filePath: "crates/typstlab-base/src/version_resolver_jsons/typst.json",
          missingKeys: ["0.14.1"],
          extraKeys: ["0.99.0"]
        }
      ]
    };
    const body = buildConsistencyIssueBody(
      result,
      keyCheckResult,
      "crates/typstlab-base/src/version_resolver_jsons/typst_version_schema.json"
    );

    const expected =
      `## 🔍 Typst Schema Consistency Report

Source file: \`crates/typstlab-base/src/version_resolver_jsons/typst_version_schema.json\`

Automatic consistency check between GitHub releases and \`typst_version_schema.json\` properties.

### ❌ Missing Versions in \`properties\` (New releases found)
The following versions exist on GitHub but are NOT defined in the schema properties:
\`0.15.0\`

### ⚠️ Extra Versions in \`properties\` (Not found on GitHub)
The following versions are defined in the schema but do NOT exist as GitHub releases (possible typos):
\`0.14.99\`

### ❌ Missing in \`required\` list
The following versions are defined in \`properties\` but are missing from the \`required\` array:
\`0.14.2\`

### ❌ Extra Versions in \`required\` list
The following versions are present in the \`required\` array but are missing from \`properties\`:
\`0.15.0\`

### ⚠️ Ignored Versions Still Present in Schema
The following versions are listed in \`version_ignores\` but still appear in \`properties\`:
\`0.11.1\`

The following versions are listed in \`version_ignores\` but still appear in \`required\`:
\`0.11.1\`

### Appendix: Resolver JSON Key Check

> Use the schema's \`required\` set as the source of truth and check each JSON file for missing or extra keys.

#### \`crates/typstlab-base/src/version_resolver_jsons/typst.json\`

##### ❌ Missing keys
\`0.14.1\`

##### ⚠️ Extra keys
\`0.99.0\`

---
*This issue was automatically generated by the CI consistency check script.*`;

    expect(body).toBe(expected);
  });
});
