import type { ConsistencyResult } from "./typst_consistency";

/**
 * Builds a Markdown body for the consistency check report.
 */
export function buildConsistencyIssueBody(result: ConsistencyResult, schemaPath: string): string {
  const sections: string[] = [];

  sections.push("## 🔍 Typst Schema Consistency Report");
  sections.push("");
  sections.push(`Source file: \`${schemaPath}\``);
  sections.push("");
  sections.push("Automatic consistency check between GitHub releases and `typst_version_schema.json` properties.");
  sections.push("");

  if (result.missingInSchema.length > 0) {
    sections.push("### ❌ Missing Versions in `properties` (New releases found)");
    sections.push("The following versions exist on GitHub but are NOT defined in the schema properties:");
    sections.push(result.missingInSchema.map((v) => `- ${v}`).join("\n"));
    sections.push("");
  }

  if (result.extraInSchema.length > 0) {
    sections.push("### ⚠️ Extra Versions in `properties` (Not found on GitHub)");
    sections.push("The following versions are defined in the schema but do NOT exist as GitHub releases (possible typos):");
    sections.push(result.extraInSchema.map((v) => `- ${v}`).join("\n"));
    sections.push("");
  }

  if (result.missingInRequired.length > 0) {
    sections.push("### ❌ Missing in `required` list");
    sections.push("The following versions are defined in `properties` but are missing from the `required` array:");
    sections.push(result.missingInRequired.map((v) => `- ${v}`).join("\n"));
    sections.push("");
  }

  if (result.extraInRequired.length > 0) {
    sections.push("### ❌ Extra Versions in `required` list");
    sections.push("The following versions are present in the `required` array but are missing from `properties`:");
    sections.push(result.extraInRequired.map((v) => `- ${v}`).join("\n"));
    sections.push("");
  }

  if (result.ignoredInProperties.length > 0 || result.ignoredInRequired.length > 0) {
    sections.push("### ⚠️ Ignored Versions Still Present in Schema");

    if (result.ignoredInProperties.length > 0) {
      sections.push("The following versions are listed in `version_ignores` but still appear in `properties`:");
      sections.push(result.ignoredInProperties.map((v) => `- ${v}`).join("\n"));
      sections.push("");
    }

    if (result.ignoredInRequired.length > 0) {
      sections.push("The following versions are listed in `version_ignores` but still appear in `required`:");
      sections.push(result.ignoredInRequired.map((v) => `- ${v}`).join("\n"));
      sections.push("");
    }
  }

  sections.push("---");
  sections.push("*This issue was automatically generated by the CI consistency check script.*");

  return sections.join("\n");
}
