name: JSON Schema Validation

on:
  push:
    branches: [ main ]
    paths:
      - "crates/typstlab-base/src/version_resolver_jsons/*.json"
      - ".github/workflows/check-version-resolve-json-schema.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "crates/typstlab-base/src/version_resolver_jsons/*.json"
      - ".github/workflows/check-version-resolve-json-schema.yml"
  workflow_dispatch:

jobs:
  validate:
    name: Validate JSON Schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Compile schema file
        run: bun run json-check:schema
        working-directory: .github/scripts

      - name: Validate resolver JSON files
        run: bun run json-check:files
        working-directory: .github/scripts
